### ISSUE TITLE
ValueError("All arguments must be passed as keyword arguments.")

### ISSUE THREAD

**Issue by okdolly-001** [phraust1612/MinervaSc2#2]
I changed several lines in trainingRL.py because the original import statements are outdated.I have an empty 'saved' directory inside MinervaSc2.

At first I ran "trainingRL.py --start_episode 0" and encountered 
```
"Restoring parameters from saved/model
2018-05-15 23:52:22.844836: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure at save_restore_tensor.cc:170: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for saved/model'
```

How is  'saved/model" generated?

I passed all args defined as FLAGS and still have "ValueError("All arguments must be passed as keyword arguments.")".

```
Old:
from pysc2.lib import app
import gflags as flags

flags.DEFINE_integer("learning_rate", 0.001, "learning rate")
flags.DEFINE_integer("discount", 0.99, "discount factor")


def _main():
    argv = FLAGS(sys.argv)
    app.really_start(main) . // This func no longer exists

```
```
New:
from absl import app
from absl import flags


flags.DEFINE_float("learning_rate", 0.001, "learning rate")
flags.DEFINE_float("discount", 0.99, "discount factor")

def _main():
    argv = FLAGS(sys.argv)
    app.run(main)
```

```
(PY36) campus-060-122:MinervaSc2 domore$ p3 trainingRL.py --start_episode 0 —num_episodes 100 —screen_size 64 —minimap_size 64  —learning_rate 0.001 —discount 0.99  —batch_size 16 —max_buffer_size 50000 —update_frequency 16 —visualize True —agent_race T —bot_race R —map_name AscensiontoAiur —difficulty 1

INFO:tensorflow:Restoring parameters from saved/model
I0515 23:41:06.231786 140736040682368 tf_logging.py:115] Restoring parameters from saved/model
2018-05-15 23:41:06.275478: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure at save_restore_tensor.cc:170: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved/model: Not found: saved; No such file or directory
DQN : no params were restored
INFO:tensorflow:Restoring parameters from saved/model
I0515 23:41:07.622834 140736040682368 tf_logging.py:115] Restoring parameters from saved/model
2018-05-15 23:41:07.699171: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure at save_restore_tensor.cc:170: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved/model: Not found: saved; No such file or directory
DQN : no params were restored
memory before starting the iteration : 389246976 (kb)
Traceback (most recent call last):
  File "trainingRL.py", line 237, in <module>
    sys.exit(_main())
  File "trainingRL.py", line 234, in _main
    app.run(main)
  File "/anaconda3/envs/PY36/lib/python3.6/site-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/anaconda3/envs/PY36/lib/python3.6/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "trainingRL.py", line 213, in main
    visualize=FLAGS.visualize) as env:
  File "/anaconda3/envs/PY36/lib/python3.6/site-packages/pysc2/env/sc2_env.py", line 116, in __init__
    raise ValueError("All arguments must be passed as keyword arguments.")
ValueError: All arguments must be passed as keyword arguments.
I0515 23:41:07.895246 140736040682368 sc2_env.py:327] Environment Close
I0515 23:41:07.895418 140736040682368 sc2_env.py:342] 
```

**Comment by hyunblnjeong** [comment]
@okdolly 
In my case,

Q1) Creating a folder named 'saved' in the directory where your trainingRL.py is located.

Q2) trainingRL.py -> def main -> with sc2_env.SC2Env
changing 'FLAGS.map_name,' to 'map_name=FLAGS.map_name,' worked.
